name: Fetch GitHub Issues

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch: # 手动触发工作流
  push:
    branches:
      - main

jobs:
  fetch-issues:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: 拉取 GitHub Issues 数据
    - name: Fetch Issues
      env:
        GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
        curl -H "Authorization: token $GITHUB_TOKEN" \
        https://api.github.com/repos/chrisxuzc/Fudan-GIANT/issues > issues.json

    # Step 3: 将更新后的 issues.json 提交回仓库
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add issues.json
        git commit -m "Update issues.json"
        git push
